version: "3"

services:

  laravel:
    image: emersonfidelon/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: emersonfidelon/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports: 
      - "8080:80"

networks:
  laranet:
    driver: bridge