version: "3"

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER="root"
      - MYSQL_PASSWORD="123"
      - MYSQL_ROOT_PASSWORD="123"
    networks: 
      - node-network

networks:
  node-network:
    driver: bridge